Repository Qiskit/qiskit-code-assistant-vscode, pull requests merged in 2018-07, with the labels that each got.

#4 Update publisher & author in package.json files
  CHANGELOG.md
  client/package.json
  package.json
  server/package.json
Labels: priority: high, status: confirmed, type: enhancement

#7 Enhancements: Update logo to the Qiskit one and update authors username & URL for Github public
  CHANGELOG.md
  client/icon.png
Labels: priority: medium, status: confirmed, type: enhancement

#6 Windows fixes: RegEx(es) & replacing pool.map
  CHANGELOG.md
  client/resources/qiskitScripts/listRemoteBackends.py
  client/src/packages/packageManager.ts
  client/src/pip/packageInfoParser.ts
Labels: priority: high, status: confirmed, type: bug

#15 Fixed client readme external references
  CHANGELOG.md
  client/README.md
Labels: priority: high, status: confirmed, type: bug

#17 Preparation for the v0.3.1
  CHANGELOG.md
  client/package.json
  package.json
  server/package.json
Labels: priority: high, status: confirmed, type: enhancement

#19 Automatic release
  .travis.yml
  client/package-lock.json
  package-lock.json
  server/package-lock.json
Labels: priority: low, status: confirmed, type: enhancement

#21 Jest at server
  CHANGELOG.md
  client/package.json
  client/src/languages.ts
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/test/compilation.test.ts
  server/test/persistentSymbolTable.test.ts
  server/test/qasmParser.test.ts
  server/test/qiskitParser.test.ts
  server/test/qiskitSemanticAnalyzer.test.ts
  server/test/qiskitSymbolTableGenerator.test.ts
  server/test/symbolTable.test.ts
  server/test/tools/tools.ts
  server/test/utils/expecter.ts
  server/test/utils/tokens.ts
  server/tsconfig.json
Labels: priority: low, status: confirmed, type: enhancement

#22 Adding tests for the client
  CHANGELOG.md
  client/package-lock.json
  client/src/__mocks__/commandExecutor.ts
  client/src/__mocks__/utils.ts
  client/src/dependencies/__mocks__/dependency.ts
  client/src/version.ts
  client/src/visualizations/__mocks__/renderBuilder.ts
  client/src/visualizations/deviceStatusVisualization.ts
  client/test/commandExecutor.test.ts
  client/test/dependencies/dependency.test.ts
  client/test/pip/packageInfoParser.test.ts
  client/test/pip/pipExecutor.test.ts
  client/test/pip/pypiExecutor.test.ts
  client/test/tools/fakePipCommandExecutor.ts
  client/test/utils.test.ts
  client/test/version.test.ts
  client/test/visualizations/deviceStatusVisualizations.test.ts
  client/test/visualizations/histogramRenderer.test.ts
  client/test/visualizations/preformattedRenderer.test.ts
  client/test/visualizations/renderBuilder.test.ts
  package-lock.json
  server/package-lock.json
Labels: priority: medium, status: confirmed, type: enhancement

#23 Updating qiskit's logo to the last version
  CHANGELOG.md
  client/icon.png
Labels: priority: medium, status: confirmed, type: enhancement

#24 Updating instructions for installing the extension
  CHANGELOG.md
  README.md
  client/README.md
Labels: priority: medium, status: confirmed, type: documentation, type: enhancement
